# Generated by Django 2.1.5 on 2019-01-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('team', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='frontend/Content/news/images/%Y/%m/%d/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('source', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='frontend/Content/news/videos/%Y/%m/%d/')),
                ('related_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('related_players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('related_teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
