# Generated by Django 2.1.3 on 2019-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190125_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='related_games',
            new_name='related_game',
        ),
        migrations.AddField(
            model_name='news',
            name='is_basketball',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
