# Generated by Django 2.1.5 on 2019-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190125_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
