# Generated by Django 2.1.5 on 2019-01-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_basketball',
            field=models.BooleanField(verbose_name='بسکتبال است'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی مرتبط'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_players',
            field=models.ManyToManyField(blank=True, to='player.Player', verbose_name='بازیکنان مرتبط'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_teams',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='تیم\u200cهای مرتبط'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(null=True, verbose_name='شرخ خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news/videos/%Y/%m/%d/', verbose_name='ویدیو'),
        ),
    ]
