# Generated by Django 2.1.5 on 2019-02-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190129_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='related_players',
        ),
    ]
