# Generated by Django 2.1.5 on 2019-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameevent_half_or_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
