# Generated by Django 2.1.5 on 2019-01-29 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
