# Generated by Django 2.1.5 on 2019-01-29 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190129_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_time',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
