# Generated by Django 2.1.5 on 2019-01-29 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190129_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_ball_possession',
            field=models.FloatField(default=0.5, verbose_name='مالکیت توپ میزبان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='team.Team', verbose_name='میهمان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_players',
            field=models.ManyToManyField(related_name='away_players', to='player.Player', verbose_name='بازیکنان تیم میهمان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ برگزاری'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='team.Team', verbose_name='میزبان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_players',
            field=models.ManyToManyField(related_name='home_players', to='player.Player', verbose_name='بازیکنان تیم میزبان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.LeagueSeason', verbose_name='لیگ'),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.IntegerField(verbose_name='هفته'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='half_or_quarter',
            field=models.IntegerField(verbose_name='نیمه/کوارتر'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='minute',
            field=models.IntegerField(verbose_name='دقیقه'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='type',
            field=models.CharField(choices=[('goal', 'گل'), ('goal_opportunity', 'موقعیت گل'), ('yellow_card', 'کارت زرد'), ('red_card', 'کارت قرمز'), ('assist', 'پاس گل'), ('2_score_goal', 'پرتاب 2 امتیازی'), ('3_score_goal', 'پرتاب 3 امتیازی'), ('foul', 'خطا'), ('rebound', 'ریباند'), ('substitution', 'تعویض'), ('penalty', 'پنالتی')], max_length=50, verbose_name='نوع رخداد'),
        ),
    ]
