# Generated by Django 2.1.5 on 2019-01-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190129_2025'),
        ('game', '0009_auto_20190129_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_player',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بهترین بازیکن میدان'),
            preserve_default=False,
        ),
    ]
