# Generated by Django 2.1.5 on 2019-01-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_best_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='best_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بهترین بازیکن میدان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_ball_possession',
            field=models.FloatField(blank=True, null=True, verbose_name='مالکیت توپ میزبان'),
        ),
    ]
