# Generated by Django 2.1.5 on 2019-02-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190201_2210'),
        ('game', '0012_auto_20190201_1818'),
    ]

    operations = [
    ]
