# Generated by Django 2.1.5 on 2019-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_merge_20190201_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.AddField(
            model_name='game',
            name='win_or_lose',
            field=models.IntegerField(default='0', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='type',
            field=models.CharField(choices=[('goal', 'گل'), ('goal_opportunity', 'موقعیت گل'), ('yellow_card', 'کارت زرد'), ('red_card', 'کارت قرمز'), ('assist', 'پاس گل'), ('2_score_goal', 'پرتاب 2 امتیازی'), ('3_score_goal', 'پرتاب 3 امتیازی'), ('foul', 'خطا'), ('rebound', 'ریباند'), ('substitution', 'تعویض'), ('penalty', 'پنالتی'), ('corner', 'کرنر')], max_length=50, verbose_name='نوع رخداد'),
        ),
    ]
