# Generated by Django 2.1.5 on 2019-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('is_basketball', models.BooleanField()),
            ],
        ),
    ]
