# Generated by Django 2.1.5 on 2019-01-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190125_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
