# Generated by Django 2.1.5 on 2019-01-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190129_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='person',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='player.Person', verbose_name='شخص'),
            preserve_default=False,
        ),
    ]
