# Generated by Django 2.1.3 on 2019-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_related_players'),
        ('player', '0007_auto_20190130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='related_news',
            field=models.ManyToManyField(blank=True, to='news.News', verbose_name='اخبار مرتبط'),
        ),
    ]
