# Generated by Django 2.1.5 on 2019-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueseason',
            options={'verbose_name': 'لیگ', 'verbose_name_plural': 'لیگ\u200cها'},
        ),
    ]
