# Generated by Django 2.1.5 on 2019-02-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_related_news'),
        ('league', '0003_auto_20190129_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueFullStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_count', models.IntegerField(verbose_name='تعداد بازی')),
                ('wins', models.IntegerField(verbose_name='برد')),
                ('draw', models.IntegerField(verbose_name='مساوی')),
                ('lose', models.IntegerField(verbose_name='باخت')),
                ('gole_zade', models.IntegerField(verbose_name='گل زده')),
                ('gole_khorde', models.IntegerField(verbose_name='گل خورده')),
                ('tafazol', models.IntegerField(verbose_name='تفاضل')),
                ('score', models.IntegerField(verbose_name='امتیاز')),
                ('leagueSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.LeagueSeason', verbose_name='فصل')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم')),
            ],
        ),
    ]
