# Generated by Django 2.1.5 on 2019-02-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_leaguefullstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguefullstatistics',
            old_name='leagueSeason',
            new_name='league_season',
        ),
    ]
