# Generated by Django 2.1.3 on 2019-01-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190125_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Person'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
