# Generated by Django 2.1.3 on 2019-01-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190125_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_basketball',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
