# Generated by Django 2.1.3 on 2019-01-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20190125_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='player',
        ),
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
