# Generated by Django 2.1.5 on 2019-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190125_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم\u200cها'},
        ),
    ]
