# Generated by Django 2.1.5 on 2019-01-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20190129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_basketball',
            field=models.BooleanField(verbose_name='بسکتبال است'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/images', verbose_name='تصویر'),
        ),
    ]
