# Generated by Django 2.1.5 on 2019-01-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('game', '0001_initial'),
        ('team', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(null=True, upload_to='accounts/images')),
                ('favorite_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('favorite_players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('favorite_teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
