# Generated by Django 2.1.5 on 2019-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, to='game.Game'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, to='player.Player'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, to='team.Team'),
        ),
    ]
