# Generated by Django 2.1.5 on 2019-01-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='accounts/images', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, to='game.Game', verbose_name='بازی\u200cهای مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, to='player.Player', verbose_name='بازیکنان مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='تیم\u200cهای مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
