# Generated by Django 2.1.5 on 2019-02-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190201_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='avatar',
        ),
    ]
